import './globals.css'
import { Archivo as Serif } from 'next/font/google'

const serif = Serif({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-serif',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${serif.variable}`}>
      <body>{children}</body>
    </html>
  )
}
